[package]
name = "blam"
version = "0.1.0"
edition = "2021"

[dependencies]
full_moon = { version = "0.19.0", features = ["lua52", "lua53", "lua54", "roblox", "stacker"] }
rayon = { version = "1.10.0" }
